version: "3.9"
services:
  database:
    image: postgres:16-alpine
    container_name: i-invest-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
  metabase:
    image: metabase/metabase:latest
    container_name: i-invest-metabase
    ports: 
      - "3000:3000"
  redis:
    image: redis:7.2-alpine
    container_name: i-invest-cache
    restart: always
    ports: 
      - "6379:6379"
volumes:
  db-data:
    driver: "local"