version: "3.9"
services:
  database:
    image: postgres:16-alpine
    container_name: investment-warlock-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: "local"